# Configuracion para despliegue en red real
server.ip=localhost
server.port=5000
server.tls.enabled=false
server.tls.keystore=certs/maria-keystore.p12
server.tls.keystore.password=changeit
server.tls.truststore=certs/maria-truststore.p12
server.tls.truststore.password=changeit
server.db.url=jdbc:sqlite:data/maria.sqlite
client.user.id=default-user
